/**
 * Data-contract parsing for the flashbook dashboard.
 *
 * The dashboard is a static export; all data arrives as JSON files under
 * `public/data/` generated by the exporter (`meta.json`, `books.json`,
 * `lag.json`, `bench.json`). These functions take the raw parsed JSON
 * (possibly malformed, partial, or `null`) and return a normalized object,
 * or `null` when the payload is unusable — the UI renders an explicit
 * "no data exported yet" state in that case.
 *
 * Plain ESM (no TypeScript) so `scripts/check.mjs` can validate the exact
 * same code paths under `node` with zero build steps.
 */

const isObj = (v) => typeof v === "object" && v !== null && !Array.isArray(v);

/** Coerce to a finite number, else the fallback (default 0). */
export function num(v, fallback = 0) {
  const n = typeof v === "string" ? Number(v) : v;
  return typeof n === "number" && Number.isFinite(n) ? n : fallback;
}

/** Coerce to a string, else the fallback (default ""). */
export function str(v, fallback = "") {
  return typeof v === "string" ? v : fallback;
}

/** Coerce to an array, else []. */
export function arr(v) {
  return Array.isArray(v) ? v : [];
}

/**
 * Normalize a timestamp of unknown precision (s / ms / us / ns since the
 * Unix epoch) to seconds. The exporter emits wall-clock values in ns and
 * per-minute buckets in s; being tolerant here keeps the dashboard from
 * silently rendering garbage axes if the unit ever changes.
 */
export function toUnixSec(t) {
  const n = num(t, 0);
  if (n <= 0) return 0;
  if (n >= 1e17) return n / 1e9; // nanoseconds
  if (n >= 1e14) return n / 1e6; // microseconds
  if (n >= 1e11) return n / 1e3; // milliseconds
  return n; // seconds
}

/** Normalize one price level `[price, qty]`; returns null if unusable. */
function level(v) {
  if (!Array.isArray(v) || v.length < 2) return null;
  const p = num(v[0], NaN);
  const q = num(v[1], NaN);
  if (!Number.isFinite(p) || !Number.isFinite(q)) return null;
  return [p, q];
}

/** Normalize a depth side (array of `[p, q]`), dropping bad levels. */
function levels(v) {
  return arr(v).map(level).filter((l) => l !== null);
}

/**
 * Parse `meta.json` → corpus + soak + instruments summary.
 * Returns null when the payload is not an object.
 */
export function parseMeta(raw) {
  if (!isObj(raw)) return null;
  const c = isObj(raw.corpus) ? raw.corpus : {};
  const s = isObj(raw.soak) ? raw.soak : {};
  return {
    generatedUnixMs: num(raw.generated_unix_ms),
    corpus: {
      events: num(c.events),
      wsFrames: num(c.ws_frames),
      spanS: num(c.span_s),
      firstWallNs: num(c.first_wall_ns),
      lastWallNs: num(c.last_wall_ns),
      rawPayloadBytes: num(c.raw_payload_bytes),
      storeBytes: num(c.store_bytes),
      bytesPerEvent: num(c.bytes_per_event),
      checksumsOk: num(c.checksums_ok),
      checksumMismatches: num(c.checksum_mismatches),
      parseErrors: num(c.parse_errors),
      gaps: num(c.gaps),
    },
    soak: {
      present: s.present === true,
      uptimeS: num(s.uptime_s),
      msgs: num(s.msgs),
      events: num(s.events),
      gaps: num(s.gaps),
      reconnects: num(s.reconnects),
      fallbacks: num(s.fallbacks),
      parseErrors: num(s.parse_errors),
      restSnaps: num(s.rest_snaps),
      rssMaxMb: num(s.rss_max_mb),
      restarts: num(s.restarts),
      perVenue: arr(s.per_venue)
        .filter(isObj)
        .map((v) => ({
          venue: str(v.venue, "?"),
          msgs: num(v.msgs),
          events: num(v.events),
          gaps: num(v.gaps),
          reconnects: num(v.reconnects),
          parseErrors: num(v.parse_errors),
        })),
    },
    instruments: arr(raw.instruments)
      .filter(isObj)
      .map((i) => ({
        id: num(i.id),
        venue: str(i.venue, "?"),
        venueSymbol: str(i.venue_symbol, "?"),
        canonical: str(i.canonical, "?"),
      })),
  };
}

/**
 * Parse `books.json` → replay window + per-instrument point series.
 * Returns null when the payload is not an object or has no series.
 */
export function parseBooks(raw) {
  if (!isObj(raw)) return null;
  const w = isObj(raw.window) ? raw.window : {};
  const series = arr(raw.series)
    .filter(isObj)
    .map((s) => ({
      instrument: num(s.instrument),
      label: str(s.label, "?"),
      points: arr(s.points)
        .filter(isObj)
        .map((p) => ({
          t: num(p.t),
          bid: num(p.bid),
          ask: num(p.ask),
          mid: num(p.mid),
          bid10: levels(p.bid10),
          ask10: levels(p.ask10),
        })),
    }))
    .filter((s) => s.points.length > 0);
  if (series.length === 0) return null;
  return {
    window: {
      startWallNs: num(w.start_wall_ns),
      endWallNs: num(w.end_wall_ns),
      stepS: num(w.step_s),
    },
    series,
  };
}

/**
 * Parse `lag.json` → per-minute venue buckets + venue-path latency rows.
 * Returns null when the payload is not an object.
 */
export function parseLag(raw) {
  if (!isObj(raw)) return null;
  return {
    perMinute: arr(raw.per_minute)
      .filter(isObj)
      .map((m) => ({
        tUnixS: num(m.t_unix_s),
        venue: str(m.venue, "?"),
        msgs: num(m.msgs),
        events: num(m.events),
        gaps: num(m.gaps),
        reconnects: num(m.reconnects),
        segmentBytes: num(m.segment_bytes),
      })),
    venuePathMs: arr(raw.venue_path_ms)
      .filter(isObj)
      .map((v) => ({
        venue: str(v.venue, "?"),
        p50: num(v.p50),
        p90: num(v.p90),
        p99: num(v.p99),
        n: num(v.n),
      })),
    queueNote: str(raw.queue_note),
  };
}

/**
 * Parse `bench.json` → availability flag + section-grouped metric rows.
 * Returns null when the payload is not an object.
 */
export function parseBench(raw) {
  if (!isObj(raw)) return null;
  return {
    available: raw.available === true,
    generatedFrom: str(raw.generated_from),
    rows: arr(raw.rows)
      .filter(isObj)
      .map((r) => ({
        section: str(r.section, "misc"),
        metric: str(r.metric, "?"),
        value: str(String(r.value ?? "")),
        unit: str(r.unit),
        sourceFile: str(r.source_file),
      })),
  };
}

/** Group bench rows by section, preserving first-seen section order. */
export function groupBenchRows(rows) {
  const order = [];
  const bySection = new Map();
  for (const r of arr(rows)) {
    if (!bySection.has(r.section)) {
      bySection.set(r.section, []);
      order.push(r.section);
    }
    bySection.get(r.section).push(r);
  }
  return order.map((section) => ({ section, rows: bySection.get(section) }));
}

/**
 * Bucket `lag.per_minute` rows into per-venue time series of a chosen
 * numeric field. Returns `[{ venue, points: [{x: unixSec, y}] }]` sorted
 * by time within each venue.
 */
export function perVenueSeries(perMinute, field) {
  const byVenue = new Map();
  for (const m of arr(perMinute)) {
    if (!isObj(m)) continue;
    const v = str(m.venue, "?");
    if (!byVenue.has(v)) byVenue.set(v, []);
    byVenue.get(v).push({ x: toUnixSec(m.tUnixS ?? m.t_unix_s), y: num(m[field]) });
  }
  return [...byVenue.entries()].map(([venue, points]) => ({
    venue,
    points: points.sort((a, b) => a.x - b.x),
  }));
}
