//! Block format v2 integration tests: v1 backward compatibility (committed
//! fixtures written by the historical v1 encoder + a byte-exact hand-rolled
//! v1 encoder for property tests), the v2 column-offset table (roundtrip,
//! corruption rejection), pruned column decodes vs full decodes, and
//! mixed-version files.
//!
//! The committed fixtures under `tests/fixtures/` were generated by the
//! pre-v2 encoder (BLOCK_VERSION = 1) from `fixture_events(700, 77)`:
//! - `v1-zstd.fbstore`: sealed segment, 256 events/block, zstd level 3
//! - `v1-raw.fbstore`: unsealed segment (checkpoint, no seal), raw blocks
//! - `v1-block-raw.bin` / `v1-block-zstd.bin`: bare `encode_block` output
//!   for `fixture_events(700, 77)[..300]`, raw and zstd(3)

use std::path::PathBuf;

use flashbook_proto::event::Event;
use flashbook_store::block::{
    BLOCK_MAGIC, BLOCK_VERSION, BLOCK_VERSION_V1, BlockError, ColumnData, ColumnSelection,
    HEADER_LEN_V1, HEADER_LEN_V2, MAX_BLOCK_EVENTS, decode_block, decode_block_columns,
    encode_block, parse_header,
};
use flashbook_store::segment::{FILE_MAGIC, FILE_VERSION, StoreReader, StoreWriter};
use flashbook_store::varint::{
    encode_delta_i64, encode_delta_u64, encode_dod_u64, encode_v_u32, encode_zz_i64,
};
use proptest::prelude::*;

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures")).join(name)
}

/// Deterministic mono-nondecreasing events the committed v1 fixtures were
/// generated from (replicated from the one-shot generator — DO NOT change:
/// the fixture bytes are frozen).
fn fixture_events(n: usize, seed: u64) -> Vec<Event> {
    let mut evs = Vec::with_capacity(n);
    let mut t = 7_000_000_000u64;
    let mut price = 4_212_345_678_900i64;
    for i in 0..n {
        let x = seed
            .wrapping_mul(0x9E37_79B9_7F4A_7C15)
            .wrapping_add((i as u64).wrapping_mul(0xBF58_476D_1CE4_E5B9));
        t += x % 800_000;
        price += ((x >> 7) % 4001) as i64 - 2000;
        evs.push(Event {
            recv_mono_ns: t,
            recv_wall_ns: t + 1_750_000_000_000_000_000,
            venue_ts_ns: t + 1_750_000_000_000_000_000 - 2_500_000,
            venue_seq: 40_000 + i as u64,
            price,
            qty: ((x >> 17) % 2_000_000) as i64,
            aux: x >> 33,
            instrument: (x % 13) as u32 + 1,
            kind: (x % 11) as u8 + 1,
            venue: (x % 3) as u8 + 1,
            flags: (x % 8) as u8,
            rsvd: 0,
        });
    }
    evs
}

/// Hand-rolled v1 block encoder: reconstructs the historical layout (56-byte
/// header, version byte 1, NO column-offset table, same column encodings).
/// Byte-exactness vs the historical encoder is asserted against the
/// committed raw fixture below; property tests then use it to feed v1
/// blocks to the new decoder.
fn encode_block_v1(events: &[Event], zstd_level: Option<i32>, out: &mut Vec<u8>) -> usize {
    assert!(!events.is_empty() && events.len() <= MAX_BLOCK_EVENTS);
    assert!(events.iter().all(|e| e.rsvd == 0));
    let mut body = Vec::new();
    encode_dod_u64(events.iter().map(|e| e.recv_mono_ns), &mut body);
    encode_dod_u64(events.iter().map(|e| e.recv_wall_ns), &mut body);
    encode_delta_u64(events.iter().map(|e| e.venue_ts_ns), &mut body);
    encode_delta_u64(events.iter().map(|e| e.venue_seq), &mut body);
    encode_delta_i64(events.iter().map(|e| e.price), &mut body);
    encode_zz_i64(events.iter().map(|e| e.qty), &mut body);
    encode_delta_u64(events.iter().map(|e| e.aux), &mut body);
    encode_v_u32(events.iter().map(|e| e.instrument), &mut body);
    body.extend(events.iter().map(|e| e.kind));
    body.extend(events.iter().map(|e| e.venue));
    body.extend(events.iter().map(|e| e.flags));

    let raw_len = u32::try_from(body.len()).unwrap();
    let (stored, zstd_used) = match zstd_level {
        Some(level) => {
            let c = zstd::bulk::compress(&body, level).unwrap();
            if c.len() < body.len() {
                (c, true)
            } else {
                (body, false)
            }
        }
        None => (body, false),
    };
    let body_len = u32::try_from(stored.len()).unwrap();

    let (mut min_m, mut max_m) = (u64::MAX, 0u64);
    let (mut min_w, mut max_w) = (u64::MAX, 0u64);
    for e in events {
        min_m = min_m.min(e.recv_mono_ns);
        max_m = max_m.max(e.recv_mono_ns);
        min_w = min_w.min(e.recv_wall_ns);
        max_w = max_w.max(e.recv_wall_ns);
    }

    let crc = crc32fast::hash(&stored);
    let start = out.len();
    out.extend_from_slice(&BLOCK_MAGIC.to_le_bytes());
    out.push(BLOCK_VERSION_V1);
    out.push(if zstd_used { 1 } else { 0 });
    out.extend_from_slice(&0u16.to_le_bytes());
    out.extend_from_slice(&u32::try_from(events.len()).unwrap().to_le_bytes());
    out.extend_from_slice(&body_len.to_le_bytes());
    out.extend_from_slice(&raw_len.to_le_bytes());
    out.extend_from_slice(&min_m.to_le_bytes());
    out.extend_from_slice(&max_m.to_le_bytes());
    out.extend_from_slice(&min_w.to_le_bytes());
    out.extend_from_slice(&max_w.to_le_bytes());
    out.extend_from_slice(&crc.to_le_bytes());
    out.extend_from_slice(&stored);
    out.len() - start
}

/// Events with fully-random field values scattered in (same trick as the
/// block unit tests: decoders must be correct for ANY input).
fn scattered_events(n: usize, seed: u64) -> Vec<Event> {
    let mut evs = fixture_events(n, seed);
    for (i, e) in evs.iter_mut().enumerate() {
        if i % 3 == 0 {
            let x = seed.wrapping_mul(i as u64 + 1);
            e.recv_mono_ns = x;
            e.recv_wall_ns = x.wrapping_mul(31);
            e.venue_ts_ns = x.wrapping_mul(17);
            e.venue_seq = x.wrapping_mul(13);
            #[allow(clippy::cast_possible_wrap)]
            {
                e.price = x.wrapping_mul(7) as i64;
            }
            #[allow(clippy::cast_possible_wrap)]
            {
                e.qty = x.wrapping_mul(3) as i64;
            }
            e.aux = x;
        }
    }
    evs
}

fn selection_from_mask(mask: u16) -> ColumnSelection {
    ColumnSelection {
        recv_mono: mask & 1 != 0,
        recv_wall: mask & 2 != 0,
        venue_ts: mask & 4 != 0,
        venue_seq: mask & 8 != 0,
        price: mask & 16 != 0,
        qty: mask & 32 != 0,
        aux: mask & 64 != 0,
        instrument: mask & 128 != 0,
        kind: mask & 256 != 0,
        venue: mask & 512 != 0,
        flags: mask & 1024 != 0,
    }
}

/// Assert `cols` holds exactly the selected projections of `events`.
fn assert_columns_match(cols: &ColumnData, sel: ColumnSelection, events: &[Event]) {
    macro_rules! check {
        ($field:ident, $ev:ident -> $get:expr) => {
            match (&cols.$field, sel.$field) {
                (Some(got), true) => {
                    let want: Vec<_> = events.iter().map(|$ev| $get).collect();
                    assert_eq!(got[..], want[..], stringify!($field));
                }
                (None, false) => {}
                (got, on) => panic!(
                    "{}: got Some={} selected={on}",
                    stringify!($field),
                    got.is_some()
                ),
            }
        };
    }
    check!(recv_mono, e -> e.recv_mono_ns);
    check!(recv_wall, e -> e.recv_wall_ns);
    check!(venue_ts, e -> e.venue_ts_ns);
    check!(venue_seq, e -> e.venue_seq);
    check!(price, e -> e.price);
    check!(qty, e -> e.qty);
    check!(aux, e -> e.aux);
    check!(instrument, e -> e.instrument);
    check!(kind, e -> e.kind);
    check!(venue, e -> e.venue);
    check!(flags, e -> e.flags);
}

/// Full scan_columns pass over a reader, checked block-by-block against
/// the same reader's Event scan.
fn assert_scan_columns_equals_scan(r: &StoreReader, sel: ColumnSelection) {
    let mut events = Vec::new();
    r.scan(|e| events.push(*e)).unwrap();
    let mut at = 0usize;
    let mut calls = 0usize;
    let visited = r
        .scan_columns(sel, |cols, n| {
            assert_columns_match(cols, sel, &events[at..at + n]);
            at += n;
            calls += 1;
        })
        .unwrap();
    assert_eq!(visited as usize, events.len());
    assert_eq!(at, events.len());
    assert_eq!(calls, r.n_blocks(), "one sink call per block");
}

#[test]
fn hand_rolled_v1_encoder_matches_committed_fixture_bytes() {
    // The raw fixture is byte-frozen output of the historical encoder; the
    // helper must reproduce it exactly (zstd fixture is checked by decode
    // below — compressed bytes depend on the zstd library version).
    let evs = fixture_events(700, 77);
    let fixture = std::fs::read(fixture_path("v1-block-raw.bin")).unwrap();
    let mut ours = Vec::new();
    let stored = encode_block_v1(&evs[..300], None, &mut ours);
    assert_eq!(stored, ours.len());
    assert_eq!(ours, fixture, "helper must replicate the v1 encoder");
}

#[test]
fn v1_fixture_blocks_parse_and_decode() {
    let evs = fixture_events(700, 77);
    for name in ["v1-block-raw.bin", "v1-block-zstd.bin"] {
        let bytes = std::fs::read(fixture_path(name)).unwrap();
        let h = parse_header(&bytes).unwrap().unwrap();
        assert_eq!(h.version, BLOCK_VERSION_V1, "{name}");
        assert_eq!(h.header_len(), HEADER_LEN_V1);
        assert_eq!(h.total_len(), bytes.len());
        assert_eq!(h.col_lens, [0u32; 11], "v1 has no offset table");
        let mut back = Vec::new();
        let (h2, used) = decode_block(&bytes, &mut back).unwrap();
        assert_eq!(h2, h);
        assert_eq!(used, bytes.len());
        assert_eq!(back, evs[..300], "{name}");
    }
}

#[test]
fn v1_fixture_pruned_decode_falls_back_correctly() {
    let evs = fixture_events(700, 77);
    let bytes = std::fs::read(fixture_path("v1-block-zstd.bin")).unwrap();
    let sel = ColumnSelection {
        recv_mono: true,
        price: true,
        qty: true,
        instrument: true,
        ..ColumnSelection::NONE
    };
    let mut cols = ColumnData::default();
    let (h, used) = decode_block_columns(&bytes, sel, &mut cols).unwrap();
    assert_eq!(h.version, BLOCK_VERSION_V1);
    assert_eq!(used, bytes.len());
    assert_columns_match(&cols, sel, &evs[..300]);
}

#[test]
fn v1_fixture_segment_sealed_zstd_reads() {
    let evs = fixture_events(700, 77);
    let r = StoreReader::open(&fixture_path("v1-zstd.fbstore")).unwrap();
    assert!(r.sealed());
    assert!(r.torn().is_none());
    assert_eq!(r.meta(), br#"{"fixture":"v1-zstd"}"#);
    assert_eq!(r.n_blocks(), 3); // 256 + 256 + 188
    assert_eq!(r.n_events(), 700);
    assert_eq!(r.verify().unwrap(), 700);
    let mut got = Vec::new();
    r.scan(|e| got.push(*e)).unwrap();
    assert_eq!(got, evs);
    let mut buf = Vec::new();
    let h = r.decode_block(0, &mut buf).unwrap();
    assert_eq!(h.version, BLOCK_VERSION_V1);
    assert_scan_columns_equals_scan(
        &r,
        ColumnSelection {
            recv_mono: true,
            price: true,
            qty: true,
            instrument: true,
            ..ColumnSelection::NONE
        },
    );
    assert_scan_columns_equals_scan(&r, ColumnSelection::ALL);
}

#[test]
fn v1_fixture_segment_unsealed_raw_recovers() {
    // No footer: the reader must index this file via the recovery scan,
    // which walks v1 (56-byte) headers.
    let evs = fixture_events(700, 77);
    let r = StoreReader::open(&fixture_path("v1-raw.fbstore")).unwrap();
    assert!(!r.sealed());
    assert!(r.torn().is_none());
    assert_eq!(r.meta(), br#"{"fixture":"v1-raw"}"#);
    assert_eq!(r.n_events(), 700);
    assert_eq!(r.verify().unwrap(), 700);
    let mut got = Vec::new();
    r.scan(|e| got.push(*e)).unwrap();
    assert_eq!(got, evs);
    assert_scan_columns_equals_scan(
        &r,
        ColumnSelection {
            recv_wall: true,
            venue_seq: true,
            kind: true,
            ..ColumnSelection::NONE
        },
    );
}

#[test]
fn mixed_v1_v2_file_scans() {
    // Hand-built unsealed segment: file header + one v1 block + one v2
    // block. Self-delimiting blocks mean versions may mix per block; every
    // read path must handle both in one file.
    let evs = fixture_events(700, 41);
    let meta = b"mx";
    let mut bytes = Vec::new();
    bytes.extend_from_slice(FILE_MAGIC);
    bytes.push(FILE_VERSION);
    bytes.push(0);
    bytes.extend_from_slice(&0u16.to_le_bytes());
    bytes.extend_from_slice(&u32::try_from(meta.len()).unwrap().to_le_bytes());
    bytes.extend_from_slice(meta);
    encode_block_v1(&evs[..300], Some(3), &mut bytes);
    encode_block(&evs[300..], None, &mut bytes).unwrap();

    let dir = tempfile::tempdir().unwrap();
    let p = dir.path().join("mixed.fbstore");
    std::fs::write(&p, &bytes).unwrap();

    let r = StoreReader::open(&p).unwrap();
    assert!(!r.sealed());
    assert!(r.torn().is_none());
    assert_eq!(r.n_blocks(), 2);
    assert_eq!(r.n_events(), 700);
    let mut buf = Vec::new();
    let h0 = r.decode_block(0, &mut buf).unwrap();
    let h1 = r.decode_block(1, &mut buf).unwrap();
    assert_eq!(
        (h0.version, h1.version),
        (BLOCK_VERSION_V1, BLOCK_VERSION),
        "one file, both block versions"
    );
    assert_eq!(buf, evs);
    assert_eq!(r.verify().unwrap(), 700);
    assert_scan_columns_equals_scan(
        &r,
        ColumnSelection {
            recv_mono: true,
            qty: true,
            venue: true,
            ..ColumnSelection::NONE
        },
    );
}

/// Read the column-length table entry `idx` of the v2 block at `bytes`.
fn get_col_len(bytes: &[u8], idx: usize) -> u32 {
    let at = HEADER_LEN_V1 + idx * 4;
    u32::from_le_bytes(bytes[at..at + 4].try_into().unwrap())
}

/// Overwrite the column-length table entry `idx` of the v2 block at `bytes`.
fn set_col_len(bytes: &mut [u8], idx: usize, len: u32) {
    let at = HEADER_LEN_V1 + idx * 4;
    bytes[at..at + 4].copy_from_slice(&len.to_le_bytes());
}

#[test]
fn corrupt_offset_table_sum_mismatch_rejected() {
    let evs = fixture_events(300, 9);
    let mut bytes = Vec::new();
    encode_block(&evs, Some(3), &mut bytes).unwrap();
    let l0 = get_col_len(&bytes, 0);
    set_col_len(&mut bytes, 0, l0 + 1); // sum != raw_len
    assert!(matches!(
        parse_header(&bytes),
        Err(BlockError::Corrupt("column lengths do not sum to raw_len"))
    ));
    let mut out = Vec::new();
    assert!(matches!(
        decode_block(&bytes, &mut out),
        Err(BlockError::Corrupt(_))
    ));
    let mut cols = ColumnData::default();
    assert!(matches!(
        decode_block_columns(&bytes, ColumnSelection::ALL, &mut cols),
        Err(BlockError::Corrupt(_))
    ));
}

#[test]
fn corrupt_offset_table_boundary_shift_rejected() {
    // Move one byte from the mono column to the wall column: the sum still
    // matches raw_len, but the mono stream no longer decodes n values in
    // exactly its recorded length — the per-column consumption check
    // catches it (the body CRC cannot: it covers the body, not the header).
    let evs = fixture_events(300, 9);
    let mut bytes = Vec::new();
    encode_block(&evs, None, &mut bytes).unwrap();
    let (l0, l1) = (get_col_len(&bytes, 0), get_col_len(&bytes, 1));
    set_col_len(&mut bytes, 0, l0 - 1);
    set_col_len(&mut bytes, 1, l1 + 1);
    assert!(parse_header(&bytes).is_ok(), "sum still matches");
    let mut out = Vec::new();
    assert!(matches!(
        decode_block(&bytes, &mut out),
        Err(BlockError::Corrupt(_))
    ));
    let mut cols = ColumnData::default();
    assert!(matches!(
        decode_block_columns(
            &bytes,
            ColumnSelection {
                recv_mono: true,
                ..ColumnSelection::NONE
            },
            &mut cols
        ),
        Err(BlockError::Corrupt(_))
    ));
}

#[test]
fn corrupt_offset_table_byte_column_rejected() {
    // Steal a byte from the instrument column for the kind column, keeping
    // the sum intact: byte columns must be exactly n_events long.
    let evs = fixture_events(300, 9);
    let mut bytes = Vec::new();
    encode_block(&evs, None, &mut bytes).unwrap();
    let (l7, l8) = (get_col_len(&bytes, 7), get_col_len(&bytes, 8));
    set_col_len(&mut bytes, 7, l7 - 1);
    set_col_len(&mut bytes, 8, l8 + 1);
    assert!(matches!(
        parse_header(&bytes),
        Err(BlockError::Corrupt("byte column length != n_events"))
    ));
}

#[test]
fn v2_header_truncation_is_torn() {
    let evs = fixture_events(64, 9);
    let mut bytes = Vec::new();
    encode_block(&evs, None, &mut bytes).unwrap();
    // Anything shorter than the v2 header (including cuts inside the
    // offset table, which a v1-era reader would have accepted as a full
    // header) is a torn tail, not garbage.
    for cut in [1, HEADER_LEN_V1 - 1, HEADER_LEN_V1, HEADER_LEN_V2 - 1] {
        assert!(
            matches!(parse_header(&bytes[..cut]), Err(BlockError::Torn(_))),
            "cut {cut}"
        );
    }
    assert!(parse_header(&bytes[..HEADER_LEN_V2]).unwrap().is_some());
}

#[test]
fn segment_recovery_treats_corrupt_offset_table_as_torn_tail() {
    let dir = tempfile::tempdir().unwrap();
    let evs = fixture_events(300, 21);

    // Unsealed store, tampered second-block table: the recovery scan must
    // stop there and report a torn tail at the block boundary.
    let p = dir.path().join("unsealed.fbstore");
    let mut w = StoreWriter::create(&p, b"", 128, None).unwrap();
    for e in &evs {
        w.append(e).unwrap();
    }
    w.checkpoint().unwrap();
    drop(w);
    let block1_off = {
        let r = StoreReader::open(&p).unwrap();
        assert_eq!(r.n_blocks(), 3);
        r.blocks()[1].file_offset as usize
    };
    let mut bytes = std::fs::read(&p).unwrap();
    let at = block1_off + HEADER_LEN_V1;
    let old = u32::from_le_bytes(bytes[at..at + 4].try_into().unwrap());
    bytes[at..at + 4].copy_from_slice(&(old + 1).to_le_bytes());
    std::fs::write(&p, &bytes).unwrap();

    let r = StoreReader::open(&p).unwrap();
    assert_eq!(r.n_blocks(), 1, "scan stops at the corrupt table");
    let torn = r.torn().unwrap();
    assert_eq!(torn.valid_bytes as usize, block1_off);
    assert_eq!(torn.reason, "column lengths do not sum to raw_len");
    let mut got = Vec::new();
    r.scan(|e| got.push(*e)).unwrap();
    assert_eq!(got, evs[..128]);

    // Sealed store, same tamper: the footer directory still loads, but
    // decoding the tampered block (and verify()) must fail.
    let p2 = dir.path().join("sealed.fbstore");
    let mut w = StoreWriter::create(&p2, b"", 128, None).unwrap();
    for e in &evs {
        w.append(e).unwrap();
    }
    w.seal().unwrap();
    let block1_off = StoreReader::open(&p2).unwrap().blocks()[1].file_offset as usize;
    let mut bytes = std::fs::read(&p2).unwrap();
    let at = block1_off + HEADER_LEN_V1;
    let old = u32::from_le_bytes(bytes[at..at + 4].try_into().unwrap());
    bytes[at..at + 4].copy_from_slice(&(old + 1).to_le_bytes());
    std::fs::write(&p2, &bytes).unwrap();
    let r = StoreReader::open(&p2).unwrap();
    assert!(r.sealed());
    assert!(r.decode_block(0, &mut Vec::new()).is_ok());
    assert!(r.decode_block(1, &mut Vec::new()).is_err());
    assert!(r.verify().is_err());
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(64))]

    /// The new decoder reads hand-rolled v1 blocks (raw and zstd) exactly
    /// like the historical decoder did, for arbitrary event shapes, and
    /// the pruned fallback equals the full decode's projections.
    #[test]
    fn v1_blocks_roundtrip_and_prune_via_fallback(
        seed in any::<u64>(),
        n in 1usize..500,
        z in any::<bool>(),
        mask in any::<u16>(),
    ) {
        let evs = scattered_events(n, seed);
        let mut bytes = Vec::new();
        encode_block_v1(&evs, if z { Some(1) } else { None }, &mut bytes);

        let mut back = Vec::new();
        let (h, used) = decode_block(&bytes, &mut back).unwrap();
        prop_assert_eq!(h.version, BLOCK_VERSION_V1);
        prop_assert_eq!(used, bytes.len());
        prop_assert_eq!(&back[..], &evs[..]);

        let sel = selection_from_mask(mask);
        let mut cols = ColumnData::default();
        let (h2, used2) = decode_block_columns(&bytes, sel, &mut cols).unwrap();
        prop_assert_eq!(h2, h);
        prop_assert_eq!(used2, bytes.len());
        assert_columns_match(&cols, sel, &evs);
    }

    /// v2 blocks: pruned decode equals the full decode's projections for
    /// arbitrary events and arbitrary selections (buffer reuse across
    /// consecutive blocks included).
    #[test]
    fn v2_pruned_equals_full_across_blocks(
        seed in any::<u64>(),
        n1 in 1usize..300,
        n2 in 1usize..300,
        z in any::<bool>(),
        mask in any::<u16>(),
    ) {
        let a = scattered_events(n1, seed);
        let b = scattered_events(n2, seed.wrapping_add(1));
        let level = if z { Some(1) } else { None };
        let mut bytes = Vec::new();
        encode_block(&a, level, &mut bytes).unwrap();
        let split = bytes.len();
        encode_block(&b, level, &mut bytes).unwrap();

        let sel = selection_from_mask(mask);
        let mut cols = ColumnData::default();
        let (ha, used_a) = decode_block_columns(&bytes, sel, &mut cols).unwrap();
        prop_assert_eq!(ha.version, BLOCK_VERSION);
        prop_assert_eq!(used_a, split);
        assert_columns_match(&cols, sel, &a);
        // same ColumnData reused for the second block
        let (hb, used_b) = decode_block_columns(&bytes[split..], sel, &mut cols).unwrap();
        prop_assert_eq!(hb.n_events as usize, n2);
        prop_assert_eq!(split + used_b, bytes.len());
        assert_columns_match(&cols, sel, &b);
    }
}
